version: "3.9"
services:
  app:
    container_name: dewett-tech-nextjs-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
