version: "3.9"
services:
  app:
    container_name: dewett-tech-nextjs-dev
    image: dewett-tech-nextjs-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3005:3001
