name: Development CI

on:
  push:
    branches: [master]

jobs:
  stop-docker-container:
    runs-on: [self-hosted, development]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Stop previous container
        run: docker-compose down
  build:
    runs-on: [self-hosted, development]
    needs: stop-docker-container
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Check if docker is installed
        run: docker --version
      - name: Build docker image
        run: docker compose up -d --build
  cleanning:
    runs-on: [self-hosted, development]
    needs: build
    steps:
      - name: Remove pulled project files
        run: rm -r /root/actions_runners/dewett-tech-nextjs-action-runner/_work/dewett-tech-nextjs/dewett-tech-nextjs/*
